/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_yad2xx_FTDIInterface */

#ifndef _Included_net_sf_yad2xx_FTDIInterface
#define _Included_net_sf_yad2xx_FTDIInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    getDeviceCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sf_yad2xx_FTDIInterface_getDeviceCount
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    getDevices
 * Signature: ()[Lnet/sf/yad2xx/Device;
 */
JNIEXPORT jobjectArray JNICALL Java_net_sf_yad2xx_FTDIInterface_getDevices
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    getLibraryVersionInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sf_yad2xx_FTDIInterface_getLibraryVersionInt
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    rescan
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_rescan
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    reload
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_reload
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    setVidPid
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_setVidPid
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    chipReset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_chipReset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    close
 * Signature: (Lnet/sf/yad2xx/Device;)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_close
  (JNIEnv *, jclass, jobject);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    clrDtr
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_clrDtr
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    clrRts
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_clrRts
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    cyclePort
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_cyclePort
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    eraseEE
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_eraseEE
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    getBitMode
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_net_sf_yad2xx_FTDIInterface_getBitMode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    getClock
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_sf_yad2xx_FTDIInterface_getClock
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    getComPortNumber
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_net_sf_yad2xx_FTDIInterface_getComPortNumber
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    getDriverVersionRaw
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_sf_yad2xx_FTDIInterface_getDriverVersionRaw
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    getLatencyTimer
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_net_sf_yad2xx_FTDIInterface_getLatencyTimer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    getMaxTransferSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_sf_yad2xx_FTDIInterface_getMaxTransferSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    getModemStatus
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_sf_yad2xx_FTDIInterface_getModemStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    getQueueStatus
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_sf_yad2xx_FTDIInterface_getQueueStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    getStatus
 * Signature: (J)Lnet/sf/yad2xx/DeviceStatus;
 */
JNIEXPORT jobject JNICALL Java_net_sf_yad2xx_FTDIInterface_getStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    getVersion
 * Signature: (J)Lnet/sf/yad2xx/ft4222/Version;
 */
JNIEXPORT jobject JNICALL Java_net_sf_yad2xx_FTDIInterface_getVersion
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    getVidPidRaw
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_sf_yad2xx_FTDIInterface_getVidPidRaw
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    gpioInit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_gpioInit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    gpioRead
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_sf_yad2xx_FTDIInterface_gpioRead
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    gpioGetTriggerStatus
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_sf_yad2xx_FTDIInterface_gpioGetTriggerStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    i2cMasterGetStatus
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_sf_yad2xx_FTDIInterface_i2cMasterGetStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    i2cMasterReset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_i2cMasterReset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    i2cMasterInit
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_i2cMasterInit
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    i2cMasterRead
 * Signature: (JI[BI)I
 */
JNIEXPORT jint JNICALL Java_net_sf_yad2xx_FTDIInterface_i2cMasterRead
  (JNIEnv *, jclass, jlong, jint, jbyteArray, jint);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    i2cMasterWrite
 * Signature: (JI[BI)I
 */
JNIEXPORT jint JNICALL Java_net_sf_yad2xx_FTDIInterface_i2cMasterWrite
  (JNIEnv *, jclass, jlong, jint, jbyteArray, jint);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    open
 * Signature: (Lnet/sf/yad2xx/Device;)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_open
  (JNIEnv *, jclass, jobject);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    purge
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_purge
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    read
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_net_sf_yad2xx_FTDIInterface_read
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    readEE
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_net_sf_yad2xx_FTDIInterface_readEE
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_reset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    resetPort
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_resetPort
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    restartInTask
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_restartInTask
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    setBaudRate
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_setBaudRate
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    setBitMode
 * Signature: (JBB)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_setBitMode
  (JNIEnv *, jclass, jlong, jbyte, jbyte);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    setBreakOff
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_setBreakOff
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    setBreakOn
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_setBreakOn
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    setChars
 * Signature: (JCZCZ)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_setChars
  (JNIEnv *, jclass, jlong, jchar, jboolean, jchar, jboolean);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    setClock
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_setClock
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    setDataCharacteristics
 * Signature: (JBBB)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_setDataCharacteristics
  (JNIEnv *, jclass, jlong, jbyte, jbyte, jbyte);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    setDeadmanTimeout
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_setDeadmanTimeout
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    setDtr
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_setDtr
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    setFlowControl
 * Signature: (JSCC)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_setFlowControl
  (JNIEnv *, jclass, jlong, jshort, jchar, jchar);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    setInterruptTrigger
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_setInterruptTrigger
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    setLatencyTimer
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_setLatencyTimer
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    setResetPipeRetryCount
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_setResetPipeRetryCount
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    setRts
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_setRts
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    setSuspendOut
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_setSuspendOut
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    setTimeouts
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_setTimeouts
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    setUSBParameters
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_setUSBParameters
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    setWakeUpInterrupt
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_setWakeUpInterrupt
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    stopInTask
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_stopInTask
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    unInitialize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_unInitialize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    write
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_net_sf_yad2xx_FTDIInterface_write
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     net_sf_yad2xx_FTDIInterface
 * Method:    writeEE
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_net_sf_yad2xx_FTDIInterface_writeEE
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
